#!/bin/bash
echo -e "\e[32m[INFO] 1. Kiểm tra mạng phân luồng AWS (my_network 1 & 2)...\e[0m"
docker network ls | grep -q "my_network_1" || echo -e "\e[31m[ERROR] Thiếu my_network_1\e[0m"
docker network ls | grep -q "my_network_2" || echo -e "\e[31m[ERROR] Thiếu my_network_2\e[0m"

echo -e "\e[33m[WARN] 2. Dọn dẹp Titan cũ (nếu có)...\e[0m"
docker rm -f titan_forever1 titan_forever2 >/dev/null 2>&1 || true

echo -e "\e[32m[INFO] 3. Đang tải Image Titan mới nhất...\e[0m"
docker pull nguyenvinhcao123/titanacc3nguyenvinhcao123:latest >/dev/null 2>&1

echo -e "\e[32m[INFO] 4. Khởi chạy Titan Node 1 (Đi qua IP A)...\e[0m"
docker run -d \
  --name titan_forever1 \
  --network my_network_1 \
  --cap-add=SYS_ADMIN \
  --dns 1.1.1.1 --dns 1.0.0.1 \
  --restart always \
  --memory="150m" --cpus="0.3" \
  --log-opt max-size=1m --log-opt max-file=2 \
  nguyenvinhcao123/titanacc2done:latest >/dev/null

echo -e "\e[32m[INFO] 5. Khởi chạy Titan Node 2 (Đi qua IP B)...\e[0m"
docker run -d \
  --name titan_forever2 \
  --network my_network_2 \
  --cap-add=SYS_ADMIN \
  --dns 1.1.1.1 --dns 1.0.0.1 \
  --restart always \
  --memory="150m" --cpus="0.3" \
  --log-opt max-size=1m --log-opt max-file=2 \
  nguyenvinhcao123/titanacc2done:latest >/dev/null

echo -e "\e[32m[INFO] ==== HOÀN TẤT THÊM TITAN NODE CHO AWS MULTI-IP ==== \e[0m"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep titan
